global using System.Text.RegularExpressions;
global using CSharpFunctionalExtensions;
global using DirectoryService.Domain.Departments.Relations;
global using DirectoryService.Domain.Departments.Relations.VO.DepartmentLocation;
global using DirectoryService.Domain.Departments.Relations.VO.DepartmentPosition;
global using DirectoryService.Domain.Departments.VO;
global using DirectoryService.Domain.Locations;
global using DirectoryService.Domain.Locations.VO;
global using DirectoryService.Domain.Positions.VO;
