global using System.Collections;
global using System.Reflection;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using CSharpFunctionalExtensions;
global using FluentValidation.Results;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Http;
global using Shared.Constants;
global using IResult = Microsoft.AspNetCore.Http.IResult;
