global using DirectoryService.Application.Locations.Command;
global using DirectoryService.Contracts.Locations.DTOs.Validators;
global using DirectoryService.Contracts.Locations.Requests;
global using DirectoryService.Domain.Interfaces.Locations.Repository;
global using DirectoryService.Domain.Locations;
global using FluentValidation;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Shared.Validation;
